=begin
From Project Euler

Each new term in the Fibonacci sequence is generated by
adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose
values do not exceed four million, find the sum of the
even-valued terms.


Authors: Mababio, M'Nkubitu, Ndemo

=end

def fn
  total = 0
  fn1 = 1
  fn2 = 1

  while fn < 4000000

    if fn2 % 2 == 0
      sums += fn2
    end

    new_fn = fn1 + fn2
    fn1, fn2 = fn2, new_fn
  end
  
end

puts "The sum of even numbers below 4000000 is" + sums 
