=begin
From Project Euler

Each new term in the Fibonacci sequence is generated by
adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose
values do not exceed four million, find the sum of the
even-valued terms.


Authors: Mababio, M'Nkubitu, Ndemo

=end

=begin
Pseudocode

Have an array with the first and second indexes filled.

i.e. fn[0] = 1, fn[1] = 1,
fn[n] = fn[n-1] + fn[n-2]
int FibonacciEven  = 0;

array size will be 1*N

while (fn[i] < 4000000){

generate the Fibonacci number

if (fn[n]%2 == 0)
 evenFn++;

put fn[i]+" "
}
We would do a for-loop for the interval given.
